version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./loan_performance.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    networks:
      - loan-dashboard-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - loan-dashboard-network

volumes:
  backend_data:

networks:
  loan-dashboard-network:
    driver: bridge